steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/rama17-05-2020/sanjay-repo/app1:tag2', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/rama17-05-2020/sanjay-repo/app1:tag2']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app1'
      - '--image'
      - 'us-central1-docker.pkg.dev/rama17-05-2020/sanjay-repo/app1:tag2'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' 
      - '--port'
      - '80'

images:
  - 'us-central1-docker.pkg.dev/rama17-05-2020/sanjay-repo/app1:tag2'

options:
  logging: CLOUD_LOGGING_ONLY




